# -*- coding: utf-8 -*-
"""firestore-rebook.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TJ_caTueCoLENhKNQBdJbidjTXS6f_Ld
"""

# !pip -qq install firebase-admin

#@title 
filePath = "/gdrive/My Drive/work/ReBook/rebook-f2aa5-firebase-adminsdk.json" #@param {type:"string"}
import firebase_admin
import os
import pandas as pd
from firebase_admin import credentials
from firebase_admin import firestore

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "secret_cred.json"
default_app = firebase_admin.initialize_app()

db = firestore.client()
ref = db.collection("users").document("leuFmdSFQjN4uZ4Yc3VBiXKBqoN2")

stream = ref.collection("books").stream()

books = [(book.id, book.to_dict()) for book in stream]
print(len(books))
for book in books:
  print(book)

#df = pd.DataFrame(data=map(lambda x:x[1],books),index=map(lambda x:x[0], books), columns=books[0][1].keys())
#df = df.reset_index()
#df.head()
#
#indexes = df[df['title'].str.contains("デザインパターン")]['index']
#print( [ref.collection("books").document(i).delete() for i in indexes] )
